#!/bin/bash
# starts/stops WhereHows stuff

start() {
	SDIR="/opt/WhereHows"
	APP="$1"
  PORT="$3"
	echo " * Starting PLAYAPP Service"

    if [ -f ${SDIR}/${APP}/target/universal/stage/RUNNING_PID ]
    then
        PID=$(cat ${SDIR}/${APP}/target/universal/stage/RUNNING_PID)

        if ps -p $PID > /dev/null
        then
            echo "   service already running ($PID)"
            exit 1
        fi
    fi

    cd ${SDIR}/${APP}

    echo "   starting..."
    nohup ./target/universal/stage/bin/wherehows -Dhttp.port=${PORT} > /home/ubuntu/application.log 2>&1&
}

stop() {
	SDIR="/opt/WhereHows"
	APP="$1"
	echo " * Stopping PLAYAPP Service"

    if [ ! -f ${SDIR}/${APP}/target/universal/stage/RUNNING_PID ]
    then
        echo "   nothing to stop"
        exit 1;
    fi

    kill -TERM $(cat ${SDIR}/${APP}/target/universal/stage/RUNNING_PID)
}

case "$2" in 
    start)
       start "$1" "$2" "$3"
       ;;
    stop)
       stop "$1" "$2"
       ;;
    restart)
       stop "$1" "$2"
       start "$1" "$2" "$3"
       ;;
  	*)
    	echo "Usage: playapp {web|backend-service} {start|stop|restart} {port}"
    	exit 1
    	;;
esac

exit 0