#!/bin/bash
# starts/stops WhereHows stuff

start() {
  if [ -z "$4" ]; then
  	SDIR="/opt/WhereHows"
  else
    SDIR="/vagrant/WhereHows"
  fi
	APP="$1"
  PORT="$3"
	echo " * Starting ${APP} Service"

    if [ -f ${SDIR}/${APP}/target/universal/stage/RUNNING_PID ]
    then
        PID=$(cat ${SDIR}/${APP}/target/universal/stage/RUNNING_PID)

        if ps -p $PID > /dev/null
        then
            echo "   service already running ($PID)"
            exit 1
        fi
    fi

    cd ${SDIR}/${APP}

    echo "   starting..."
    case $APP in
      web)
        nohup ./target/universal/stage/bin/wherehows -Dhttp.port=${PORT} -Ddiet=true > /home/ubuntu/${APP}.log 2>&1&
        ;;
      backend-service)
        nohup ./target/universal/stage/bin/backend-service -Dhttp.port=${PORT} -Ddiet=true > /home/ubuntu/${APP}.log 2>&1&
        ;;
    esac
}

stop() {
  if [ -z "$3" ]; then
    SDIR="/opt/WhereHows"
  else
    SDIR="/vagrant/WhereHows"
  fi
	APP="$1"
	echo " * Stopping ${APP} Service"

    if [ ! -f ${SDIR}/${APP}/target/universal/stage/RUNNING_PID ]
    then
        echo "   nothing to stop"
        exit 1;
    fi

    kill -TERM $(cat ${SDIR}/${APP}/target/universal/stage/RUNNING_PID)
}

case "$2" in 
    start)
       start "$1" "$2" "$3" "$4"
       ;;
    stop)
       stop "$1" "$2" "$3"
       ;;
    restart)
       stop "$1" "$2" "$3"
       start "$1" "$2" "$3" "$4"
       ;;
  	*)
    	echo "Usage: playapp {web|backend-service} {start|stop|restart} {port} {dev}"
    	exit 1
    	;;
esac

exit 0